owner: educup
repo: status-page

skipDescriptionUpdate: false
skipTopicsUpdate: false
skipHomepageUpdate: false

sites:
  - name: Educup Website
    url: https://www.educup.com
  - name: Educup Admin
    url: https://admin.educup.io
  - name: Educup Apps
    url: https://apps.educup.io
  - name: Educup API 
    url: https://api.educup.io/health
  - name: Educup Tutors API 
    url: https://tutorsapi.educup.io/health
  - name: Educup Studio API 
    url: https://studioapi.educup.io/health
  - name: Educup Extenal API
    url: https://externalapi.educup.io/health
    
assignees:
  - rmarticedeno
  - leynier

status-website:
  name: Educup Status
  cname: status.educup.io
  logoUrl: https://educup.com/images/vilin.ico
  favicon: https://educup.com/images/vilin.ico
  theme: night

i18n:
  footer: ""
