owner: educup
repo: status-page

skipDescriptionUpdate: false
skipTopicsUpdate: false
skipHomepageUpdate: false

sites:
  - name: EducUp Website
    url: https://www.educup.com
  - name: EducUp Admin
    url: https://admin.educup.io
  - name: EducUp Apps
    url: https://apps.educup.io
  - name: EducUp API 
    url: https://api.educup.io/health
  - name: EducUp Studio API 
    url: https://studioapi.educup.io/health
  - name: EducUp Extenal API
    url: https://externalapi.educup.io/health
    
assignees:
  - rmarticedeno
  - leynier

status-website:
  name: EducUp Status
  cname: status.educup.io
  logoUrl: https://educup.com/images/vilin.ico
  favicon: https://educup.com/images/vilin.ico
  theme: ocean

i18n:
  footer: ""
